language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t amiras1/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true amiras1/react-test npm test
after_success:
    - docker build -t amiras1/multi-client ./client
    - docker build -t amiras1/multi-nginx ./nginx
    - docker build -t amiras1/multi-worker ./worker
    - docker build -t amiras1/multi-server ./server
    - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push amiras1/multi-client
    - docker push amiras1/multi-nginx
    - docker push amiras1/multi-worker
    - docker push amiras1/multi-server    
